name: RunAsConsole
author: Rysieeku
version: 1.3
main: Rysieeku\RunAsConsole\Main
api: [3.0.0-ALPHA6]
commands:
  console:
    description: Use command as console
  runasconsole:
    description: Info about plugin
    aliases: [rac]
permissions:
  rac.use:
    default: op
  rac.info:
    default: op
  rac.*:
    default: op
