name: RunAsConsole
author: [VMPE Development Team]
version: 1.4-B1
main: Rysieeku\RunAsConsole\Main
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
commands:
  console:
    description: Use command as console
  runasconsole:
    description: Info about plugin
    aliases: [rac]
permissions:
  runasconsole.use:
    default: op
  runasconsole.info:
    default: op
  runasconsole.*:
    default: op
